# Generated by Django 3.0.3 on 2020-03-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200310_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('GR', 'General'), ('WO', 'Work'), ('BU', 'Business'), ('FD', 'Food'), ('MV', 'Movies'), ('BK', 'Books'), ('MO', 'Mom'), ('TR', 'Travel'), ('LS', 'Lifestyle'), ('DI', 'Diy'), ('PA', 'Parenting'), ('SC', 'Social'), ('ST', 'Study')], default='GR', max_length=255),
        ),
    ]
